name: swee
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  image_picker: ^1.2.2
  image_cropper: ^8.0.2
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  flutter_local_notifications: ^22.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.4

flutter_native_splash:
  color: "#F8F9FA"
  image: assets/images/logo.png
  color_dark: "#001226"
  image_dark: assets/images/logo.png
  
  fullscreen: true

  android_12:
    image: assets/images/logo.png
    color: "#F8F9FA"
    image_dark: assets/images/logo.png
    color_dark: "#001226"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/default_post.jpg
    - assets/images/default_profile.png

flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#002366"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21
