// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvnPR1p_Qn3nxKqW439od75Dy7738q9EU',
    appId: '1:975146007258:web:52aebfdc094b81db9ec3e3',
    messagingSenderId: '975146007258',
    projectId: 'swee-8966a',
    authDomain: 'swee-8966a.firebaseapp.com',
    storageBucket: 'swee-8966a.firebasestorage.app',
    measurementId: 'G-9HLZQFLMEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCtQS2pvV6j6tmeaL1qN7YJVMhB3FppvA',
    appId: '1:975146007258:android:6c3cef41bc520e9d9ec3e3',
    messagingSenderId: '975146007258',
    projectId: 'swee-8966a',
    storageBucket: 'gs://swee-8966a.firebasestorage.app',
  );
}
